### ISSUE TITLE
Does not read Sony ARW format

### ISSUE THREAD

**Issue by ppbrown** [ImpulseAdventure/JPEGsnoop#45]
I notice that it handles lots of raw image types, but NOT .ARW?
Please add

**Comment by ImpulseAdventure** [comment]
Hi @ppbrown -- thanks for the request to support Sony raw files. JPEGsnoop is primarily targeted at decoding JPEG compressed images, and doesn't decode the main content of RAW formats. That said, JPEGsnoop can still locate and decode the embedded JPEG "preview" images that are often included within the RAW containers (such as Canon CR2/CRW and even Sony ARW). Just select "Tools -> Image Search Fwd" in order to perform this search. As it is less likely that I will have the opportunity to add direct decoding support for these proprietary formats, I will close the ticket, though I am certainly open to another developer reopening this ticket if they are keen on introducing basic RAW parsing functionality.
